[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"
  SHEETDB_API_URL = ""

[[plugins]]
  package = "./netlify-plugin-env-replace"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 