[build]
  publish = "."
  command = "pip install -r requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.9"
  SHEETDB_API_URL = ""

[[plugins]]
  package = "./netlify-plugin-env-replace"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 