[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "./netlify-plugin-env-replace.js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 